### ISSUE TITLE
OnMatrixRoomEventReceived never called

### ISSUE THREAD

**Issue by squidink7** [baking-bad/matrix-dotnet-sdk#7]
I just downloaded this library to try and make a simple bot by following the guide one the README, however the program never calls the room event received method. It connects and sends the "testing..." message perfectly, but is unable to detect when someone else sends a message in that same room.

```
class Program {
	static IMatrixClient Client = new MatrixClientFactory().Create();

	static async Task Main() {
		await Client.LoginAsync(new Uri("https://matrix-client.matrix.org/"), "[USERNAME]", "[PASSWORD]", "Bot");
		Client.OnMatrixRoomEventsReceived += OnMessage;
		Client.Start();
		await Client.JoinTrustedPrivateRoomAsync("[ROOM_ID]");
		await Client.SendMessageAsync("[ROOM_ID]", "testing...");
		await Task.Delay(-1);
	}

	static void OnMessage(object? sender, MatrixRoomEventsEventArgs e) {
		Console.WriteLine("Event received");
		foreach (BaseRoomEvent roomEvent in e.MatrixRoomEvents) {
			if (roomEvent is not TextMessageEvent textMessageEvent)
				continue;

			(string roomId, string senderUserId, string message) = textMessageEvent;
			if (Client?.UserId != senderUserId)
				Console.WriteLine($"RoomId: {roomId} received message from {senderUserId}: {message}.");
		}
	}
}
```

**Comment by squidink7** [comment]
Fixed by #8

**Comment by kimimaru4000** [comment]
I've started integrating Matrix into an application, and unfortunately I'm getting this same problem. I've tried the fork from @squidink7, but unfortunately the issue persists there. I'm testing with the matrix.org homeserver at `https://matrix-client.matrix.org`, which is currently using version 1.6 of the spec.

Here's my code:
- [OnMatrixRoomEventsReceived handler](https://codeberg.org/kimimaru/TRBot/src/commit/d552ac3dc0c97e99f10bd49509ada37e5cc08693/TRBot/TRBot.Connection/ClientServices/Matrix/MatrixClientService.cs#L250) and its [subscription](https://codeberg.org/kimimaru/TRBot/src/commit/d552ac3dc0c97e99f10bd49509ada37e5cc08693/TRBot/TRBot.Connection/ClientServices/Matrix/MatrixClientService.cs#L102).
- Client is connected and started [here](https://codeberg.org/kimimaru/TRBot/src/commit/d552ac3dc0c97e99f10bd49509ada37e5cc08693/TRBot/TRBot.Connection/ClientServices/Matrix/MatrixClientService.cs#L164). I have confirmed that it's in the room, as it can send a message with no issues.

Also, `Client.GetJoinedRoomsIdsAsync()` still returns an empty list no matter what, as noted in [#2](https://github.com/baking-bad/matrix-dotnet-sdk/issues/2#issuecomment-1083094631) after it was closed.

I've [added a logger](https://codeberg.org/kimimaru/TRBot/src/commit/d552ac3dc0c97e99f10bd49509ada37e5cc08693/TRBot/TRBot.Connection/ClientServices/Matrix/MatrixClientService.cs#L99) but it's not showing anything at all - unsure if I'm doing it wrong.

I would be happy to help debug the issue and get it fixed with some guidance. Thank you!
